version: '3'

dotenv: ['.env']

tasks:
  run:
    cmds:
      - fastapi dev main.py

  migrate.new:
    cmds:
      - migrate create -ext sql -dir ./migrations -seq -digits 3 {{.CLI_ARGS}}

  migrate.up:
    cmds:
      - migrate -path ./migrations -database $DATABASE_URL up {{.CLI_ARGS}}

  migrate.down:
    cmds:
      -  migrate -path ./migrations -database $DATABASE_URL down {{.CLI_ARGS}}

  migrate.force:
    cmds:
      - migrate -path ./migrations -database $DATABASE_URL force {{.CLI_ARGS}}

  start.aider:
    cmds:
      - aider --4o --openai-api-key $GPT_KEY

  test.main:
    dotenv: ['.env_test']
    cmds:
      - migrate -path ./migrations -database $DATABASE_URL up {{.CLI_ARGS}}
      - pytest tests/test_main.py
      - migrate -path ./migrations -database $DATABASE_URL down {{.CLI_ARGS}}
